### ISSUE TITLE
Square wave latency summand

### ISSUE THREAD

**Issue by szkf** [kffl/speedbump#16]
Hi,

I can see that the square wave latency summand is planned in the [roadmap](https://github.com/kffl/speedbump/discussions/15):

> Additional latency summands (i.e. triangle wave and square wave)

I would like to implement it.

**Comment by kffl** [comment]
Sure, go ahead!

There is one caveat regarding square wave implementation. Please make sure that latency value that it generates cycles between +amplitude and -amplitude (not +amplitude/2 and -amplitude/2) to keep it consistent with other latency summands, as I've seen some publications in which the square wave amplitude was defined as the latter.
