### ISSUE TITLE
Allow providing interface to bind to e.g. 127.0.0.1?

### ISSUE THREAD

**Issue by cmawhorter** [kffl/speedbump#26]
Happy to find this today.

My understanding of go isn't the greatest, but it looks like this listens on all available interfaces.  Is it possible to specify the network interface? Or somehow only bind to loopback?

**Comment by kffl** [comment]
Hi @cmawhorter !

Sorry for a delayed response. You are right that as of now speedbump binds to all available network interfaces. While it is a common practice for containerized apps to listen on all interfaces, I can see how it may be desirable to specify a single network interface, especially when running speedbump as a binary.

I've just opened a PR adding a `--host` cli option which allows for specifying the IP address/hostname associated with a network interface on which to listen.
